--- #YAML:1.0
name:               Test-HTTP-Server
version:            0.01
abstract:           simple forking http server
author:
    - Przemysław Iskra <sparky at pld-linux.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
resources:
    repository:  https://github.com/sparky/perl-Test-HTTP-Server
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
